# Generated by Django 4.2.8 on 2024-04-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Content',
            field=models.TextField(default='Your Content here'),
        ),
        migrations.AddField(
            model_name='notes',
            name='Title',
            field=models.TextField(default='Your Title here'),
        ),
    ]
