# Generated by Django 4.2.8 on 2024-04-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_alter_notes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.users'),
        ),
    ]
