# Generated by Django 4.2.8 on 2024-04-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_alter_notes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Email',
            new_name='User',
        ),
    ]
