# Generated by Django 2.2.28 on 2024-04-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_auto_20240409_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Readaccess',
        ),
    ]
