# Generated by Django 2.2.28 on 2024-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0010_notes_readaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Readaccess',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
